### ISSUE TITLE
Wrong currency formatting

### ISSUE THREAD

**Issue by nikglobocnik** [gerbiceva/PivoTracker#2]
Badge-i za dolg/vso pivo imajo € v napačnem formatu npr. `€0.00 €` in `€0.00`. Predlagam format `0.00 €`.

**Comment by gendestry** [comment]
@LanVukusic

**Comment by LanVukusic** [comment]
@gendestry Mislim da je nik jasno hotel povedat da ti specificno to fiksas.
@nikglobocnik, potrdi

**Comment by LanVukusic** [comment]
@nikglobocnik format je popravljen in izgleda tako:

![image](https://github.com/gendestry/PivoTracker/assets/13378639/1fc0e2b1-518d-47ba-80cf-0352e0d5de1a)

Zapiram
